' This code was generated by T4 tool. Any changes made manually will be lost
' the next time this code is regenerated.

Imports System.Reflection
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices

<assembly: AssemblyFileVersion("1.0.7162.36028")>
